baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hallo"

[Author]
  name = "Reece"

[params]
    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/"
    [params.colors]
        background = "#81c6ff"
        foreground = "#edf7ff"
        hover = "#ffba82"
